# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet iis

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: SFSimulator.Web/package-lock.json
    - run: |
        cd SFSimulator.Web
        npm install
    - name: npm build
      run: |
        cd SFSimulator.Web
        npm run build
    - name: Restore
      run: dotnet restore
    - name: Build API
      run: dotnet build .\SFSimulator.API --no-restore
    - name: dotnet publish 
      run: dotnet publish -c Release -o sfsimulator .\SFSimulator.API
        
    - name: deploy on iis
      uses: ChristopheLav/iis-deploy@v1
      with:
        website-name: 'sfsimulator.xyz'
        msdeploy-service-url: ${{ secrets.IISURL }}
        msdeploy-username: ${{ secrets.IISUSER }}
        msdeploy-password: ${{ secrets.IISPASSWORD }}
        source-path: sfsimulator
